const banners = [
	{
		id: 1,
		src: '/assets/images/goods/goods (26).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'SIMPLIFY YOUR LIFE',
		description: 'JUST FOCUS',
	},
	{
		id: 2,
		src: '/assets/images/eql/28_28833_6_KOR_20230530094213.jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'ENJOY YOUR LIFE',
		description: 'JUST A FEELING',
	},
	{
		id: 3,
		src: '/assets/images/eql/33_138_10_KOR_20230525131845.jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'COOL WITH YOU',
		description: 'HMM...',
	},
	{
		id: 4,
		src: '/assets/images/eql/28_121113_1_KOR_20230526100134.jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'SIMPLIFY YOUR LIFE',
		description: 'JUST FOCUS',
	},
	{
		id: 5,
		src: '/assets/images/eql/28_28370_1_KOR_20230530094458.jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'ENJOY YOUR LIFE',
		description: 'JUST A FEELING',
	},
	{
		id: 6,
		src: '/assets/images/eql/28_121117_1_KOR_20230531094422.jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
		title: 'COOL WITH YOU',
		description: 'HMM...',
	},
]

const brands = [
	{
		id: 1,
		brand: 'Cozy Dream Corner',
		src: '/assets/images/goods/goods (1).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 2,
		brand: 'Flutter & Fluff',
		src: '/assets/images/goods/goods (2).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 3,
		brand: 'Petal Pompom Place',
		src: '/assets/images/goods/goods (3).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 4,
		brand: 'Darling Trinket Trove',
		src: '/assets/images/goods/goods (4).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 5,
		brand: 'Whimsy Wonderland',
		src: '/assets/images/goods/goods (5).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 6,
		brand: 'Fuzzy Feels Haven',
		src: '/assets/images/goods/goods (6).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 7,
		brand: 'Charming Little Nook',
		src: '/assets/images/goods/goods (7).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 8,
		brand: 'Miniature Joy Lane',
		src: '/assets/images/goods/goods (8).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 9,
		brand: 'Tiny Treasures Cottage',
		src: '/assets/images/goods/goods (9).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 10,
		brand: 'Dainty Delightful Den',
		src: '/assets/images/goods/goods (10).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 11,
		brand: 'Tiny Joy Shop',
		src: '/assets/images/goods/goods (11).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 12,
		brand: 'Petal Adorbs',
		src: '/assets/images/goods/goods (12).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 13,
		brand: 'Sweet Whims',
		src: '/assets/images/goods/goods (13).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 14,
		brand: 'Petite Gems',
		src: '/assets/images/goods/goods (14).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 15,
		brand: 'Cutesy Haven',
		src: '/assets/images/goods/goods (15).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 16,
		brand: 'Little Charmers',
		src: '/assets/images/goods/goods (16).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 17,
		brand: 'Adora Bits',
		src: '/assets/images/goods/goods (17).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 18,
		brand: 'Mini Wonders',
		src: '/assets/images/goods/goods (18).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 19,
		brand: 'Tiny Treasure Nook',
		src: '/assets/images/goods/goods (19).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 20,
		brand: 'Quirky Kitsch',
		src: '/assets/images/goods/goods (20).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 21,
		brand: 'camperz',
		src: '/assets/images/goods/goods (21).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 22,
		brand: '얼렁뚱땅소품샵',
		src: '/assets/images/goods/goods (22).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 23,
		brand: '010101',
		src: '/assets/images/goods/goods (23).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
	{
		id: 24,
		brand: 'me===1000재',
		src: '/assets/images/goods/goods (24).jpg',
		alt: '',
		url: '/',
		ariaLabel: '',
	},
]

const products = [
	{
		id: 0,
		brand: '체리쥬빌레 체리쥬빌레',
		src: '/assets/images/goods/goods (25).jpg',
		name: '양말',
		price: '3000',
		url: '/',
		stock: 1,
	},
	{
		id: 1,
		brand: 'abcde',
		src: '/assets/images/goods/goods (26).jpg',
		name: 'deantlbbbbbbbbbbbbbbbbb tlbbbbbbbbbbbbbbbtlbbbbbbbbbbbbbb bbbbbbbbtlbbbbbbb',
		price: '50000',
		url: '/',
		stock: 0,
	},
	{
		id: 2,
		brand: 'abcde',
		src: '/assets/images/goods/goods (27).jpg',
		name: 'deantlbbbbbbbbbbb',
		price: '50000',
		url: '/',
		stock: 2,
	},
	{
		id: 3,
		brand: 'abcde',
		src: '/assets/images/goods/goods (28).jpg',
		name: 'deantlbbbbbbbbbbb',
		price: '50000',
		url: '/',
		stock: 2,
	},
	{
		id: 4,
		brand: 'abcde',
		src: '/assets/images/goods/goods (29).jpg',
		name: 'deantlbbbbbbbbbbb',
		price: '50000',
		url: '/',
		stock: 2,
	},
	{
		id: 5,
		brand: 'abcde',
		src: '/assets/images/goods/goods (30).jpg',
		name: 'deantlbbbbbbbbbbb',
		price: '50000',
		url: '/',
		stock: 2,
	},
	{
		id: 6,
		brand: 'abcde',
		src: '/assets/images/goods/goods (31).jpg',
		name: 'deantlbbbbbbbbbbb',
		price: '50000',
		url: '/',
		stock: 2,
	},
]

export { banners, brands, products }
